#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#    Jun 16, 2023 02:41:15 PM +0630  platform: Windows NT

import sys, os
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import home_gui

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = home_gui.Toplevel1(_top1)
    root.mainloop()

def open_balance_test(*args):
    if _debug:
        print('main_pg_support.open_balance_test')
        root.destroy()
        os.system(r'python proj\balance_test\balance_ui.py')

        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()

def open_sitstand_test(*args):
    if _debug:
        print('main_pg_support.open_sitstand_test')
        root.destroy()
        os.system(r'python proj\sit_stand\uiupdated.py')

        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()

def open_speed_test(*args):
    if _debug:
        print('main_pg_support.open_speed_test')
        root.destroy()
        os.system(r'python proj\speed_test\speed_test.py')     

        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()

def destroy_home():
    root.destroy()

if __name__ == '__main__':
    home_gui.start_up()




